        arguments = /afs/cern.ch/user/a/ahingraj/private/analysis/CMSSW_13_0_5/src/cmsdijet/files_input/pPb_8160/DATA_HM250/Pbgoing//HM250_Pbgoing_Split//file _PD1_0.root 0 0 1 0 0
        output = condor/logs/_PD1_0.out
        error = condor/logs/_PD1_0.err
        log = condor/logs/_PD1_0.log
        queue
        arguments = /afs/cern.ch/user/a/ahingraj/private/analysis/CMSSW_13_0_5/src/cmsdijet/files_input/pPb_8160/DATA_HM250/Pbgoing//HM250_Pbgoing_Split//file _PD1_0.root 0 0 1 0 0
        output = condor/logs/_PD1_0.out
        error = condor/logs/_PD1_0.err
        log = condor/logs/_PD1_0.log
        queue
        arguments = /afs/cern.ch/user/a/ahingraj/private/analysis/CMSSW_13_0_5/src/cmsdijet/files_input/pPb_8160/DATA_HM250/Pbgoing//HM250_Pbgoing_Split//file _PD1_0.root 0 0 1 0 0
        output = condor/logs/_PD1_0.out
        error = condor/logs/_PD1_0.err
        log = condor/logs/_PD1_0.log
        queue
