universe   = vanilla
getenv     = True
executable = run_DijetAnapPb.sh
+JobFlavour           = "longlunch"
requirements = ((OpSysAndVer =?= "AlmaLinux9") && (CERNEnvironment =?= "qa"))
RequestCpus = 3

log        = cond/pthat30_unemb_pgoing_nocut.log
output     = cond/pthat30_unemb_pgoing_nocut.out
error      = cond/pthat30_unemb_pgoing_nocut.err
arguments = ../files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat30_pgoing_unembedded.txt /eos/user/a/ahingraj/outputs/Unemb_nocut_pPb_30_50.root 1 0 0 30.0 50.0
queue

log        = cond/pthat50_unemb_pgoing_nocut.log
output     = cond/pthat50_unemb_pgoing_nocut.out
error      = cond/pthat50_unemb_pgoing_nocut.err
arguments = ../files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat50_pgoing_unembedded.txt /eos/user/a/ahingraj/outputs/Unemb_nocut_pPb_50_80.root 1 0 0 50.0 80.0
queue

log        = cond/pthat80_unemb_pgoing_nocut.log
output     = cond/pthat80_unemb_pgoing_nocut.out
error      = cond/pthat80_unemb_pgoing_nocut.err
arguments = ../files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat80_pgoing_unembedded.txt /eos/user/a/ahingraj/outputs/Unemb_nocut_pPb_80_120.root 1 0 0 80.0 120.0
queue

log        = cond/pthat120_unemb_pgoing_nocut.log
output     = cond/pthat120_unemb_pgoing_nocut.out
error      = cond/pthat120_unemb_pgoing_nocut.err
arguments = ../files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat120_pgoing_unembedded.txt /eos/user/a/ahingraj/outputs/Unemb_nocut_pPb_120_170.root 1 0 0 120.0 170.0
queue

log        = cond/pthat170_unemb_pgoing_nocut.log
output     = cond/pthat170_unemb_pgoing_nocut.out
error      = cond/pthat170_unemb_pgoing_nocut.err
arguments = ../files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat170_pgoing_unembedded.txt /eos/user/a/ahingraj/outputs/Unemb_nocut_pPb_170_220.root 1 0 0 170.0 220.0
queue

log        = cond/pthat220_unemb_pgoing_nocut.log
output     = cond/pthat220_unemb_pgoing_nocut.out
error      = cond/pthat220_unemb_pgoing_nocut.err
arguments = ../files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat220_pgoing_unembedded.txt /eos/user/a/ahingraj/outputs/Unemb_nocut_pPb_220_280.root 1 0 0 220.0 280.0
queue

log        = cond/pthat280_unemb_pgoing_nocut.log
output     = cond/pthat280_unemb_pgoing_nocut.out
error      = cond/pthat280_unemb_pgoing_nocut.err
arguments = ../files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat280_pgoing_unembedded.txt /eos/user/a/ahingraj/outputs/Unemb_nocut_pPb_280_370.root 1 0 0 280.0 370.0 
queue

log        = cond/pthat370_unemb_pgoing_nocut.log
output     = cond/pthat370_unemb_pgoing_nocut.out
error      = cond/pthat370_unemb_pgoing_nocut.err
arguments = ../files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat370_pgoing_unembedded.txt /eos/user/a/ahingraj/outputs/Unemb_nocut_pPb_370_460.root 1 0 0 370.0 460.0
queue

log        = cond/pthat460_unemb_pgoing_nocut.log
output     = cond/pthat460_unemb_pgoing_nocut.out
error      = cond/pthat460_unemb_pgoing_nocut.err
arguments = ../files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat460_pgoing_unembedded.txt /eos/user/a/ahingraj/outputs/Unemb_nocut_pPb_460_540.root 1 0 0 460.0 540.0
queue

log        = cond/pthat540_unemb_pgoing_nocut.log
output     = cond/pthat540_unemb_pgoing_nocut.out
error      = cond/pthat540_unemb_pgoing_nocut.err
arguments = ../files_input/pPb_8160/MC_Unembedded/pgoing/MC_pthat540_pgoing_unembedded.txt /eos/user/a/ahingraj/outputs/Unemb_nocut_pPb_540.root 1 0 0 540.0 8160.0
queue
